### ISSUE TITLE
QEnttecPro and Qt

### ISSUE THREAD

**Issue by Caradryane** [thomasgeissl/QEnttecPro#1] opened 2016-08-12 13:48 UTC
Good morning @thomasgeissl 

I saw your work about the QEnttecPro which is good.
I'm currently doing a little project for myself, i'm trying to pilot through a Qt Project a DMX lamp, i was trying to use QDmx light but it is not possible due to the fact tha it uses .a library and i'm using C++ language through visual studio.
So i wanted to know may i use your code to control my lamp or i have to buy an entec pro to be able to use your code ?
Because right now i only have a DMX/USB cable to allow me to link my computer to the lamp ?
Thanks for your time and work .
Caradryan

**Comment by thomasgeissl** [comment] 2016-08-12 20:31
@Caradryane QEnttecPro will just work with an enttec pro device. You can check if your device is compatible with the enttec pro protocol, but I doubt that. The [manual](https://www.enttec.com/docs/dmxusbpro_manual.pdf) should give you more information. If you dont mind using openframeworks, you could try [ofxGenericDmx](https://github.com/woutgg/ofxGenericDmx). You could also use QEnttecPro as the base for a new library and just modify some parts to work with your dmx interface. Also, I often used an arduino and a dmx shield in the past and implemented a custom serial protocol or used OSC. Which is way cheaper than buying an enttec pro device.
I am going to close this, but dont hesitate to ask if things are unclear.
Thomas

**Closed as completed by thomasgeissl** 2016-08-12 20:31 UTC

**Comment by Caradryane** [comment] 2016-08-16 13:20
Good afternoon@thomasgeissl 

Thanks for your answer, i understand everything you explained, excepte the point with the open framework ? I don't know how i could use it, because i'm currently using Qt as framework with visual studio 2010, what i would like to do is to import the .libs, .h, .cpp, and DLL, like this i could add it simply to my project.
Moreover i read the manuel you were true , my device is not compatible with the entec PRO.

Have a great afternoon and one more time thanks you for your help.

**Comment by thomasgeissl** [comment] 2016-08-16 16:38
It is not that easy to integrate openframeworks into another app. But you could try if the addon i mentioned works with your device and if this is the cause, it should not be to hard to port the code to qt.

**Comment by Caradryane** [comment] 2016-08-16 16:53
Yeah i 'm going to try your solution.
Thanks for your help

**Comment by Caradryane** [comment] 2016-08-17 08:59
Hi @thomasgeissl 

I have a question your code only works with the enttec pro or with all the interface DMX from Enttec ? ( example : http://www.esl-france.com/controle/7077-enttec-open-dmx-usb-widget-boxed.html#.V7QlgZiLTIV) ?
Because if it is too hard to add the addon i will have to buy one and the cheaper would be better.
